name: CI
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - 
        name: Build Dockerfile
        uses: docker/build-push-action@v2
        with:
          load: true
          platforms: linux/amd64,linux/arm/v7
          tags: fgierlinger/git-sync:latest
          file: ./Dockerfile.armhf
      -
        name: Push Dockerfile
        #if: github.event_name == 'push'
        run: |
          docker push fgierlinger/git-sync:latest
